language: node_js
node_js:
- 4.2.0
env:
- NODE_ENV=test
cache:
  directories:
  - node_modules
services:
  - mongodb
before_install:
- 
before_script:
  - sleep 15
  - mongo bandout --eval 'db.addUser("travis", "test");'

